version: '3'
services:
    postgres:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: testi
        volumes:
            - ./postgresql/data:/var/lib/postgresql/data
    server:
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
        ports:
            - "3001:3001"
    client:
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./client:/app
        ports:
            - "3000:3000"